name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['14', '16', '18', '20']
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: npm
      - run: npm install
      - run: npm test

